# Site
name: "Blog"
title: "Goutham Reddy's Blog"
description: "My Tech Journey."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: ""
google_analytics: 'UA-46278016-1'
disqus: 'Goutham Reddy Blog'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
slugify_mode: default

# Authors
authors:
  goutham:
    name: Goutham Reddy
    display_name: Goutham Reddy
    avatar: goutham-reddy.jpeg
    gravatar: gouthamreddy51297
    email: contact@gouthamreddy.com
    web: https://gouthamreddy.com
    twitter: https://twitter.com/iamgouthamreddy
    description: "zero"
  umesh:
    name: Umesh Chandra
    display_name: Umesh Chandra
    avatar: umesh.jpg
    gravatar: gouthamreddy51297
    email: contact@gouthamreddy.com
    web: https://gouthamreddy.com
    twitter: https://twitter.com/iamgouthamreddy
    description: "Devops Engineer"
  pragati:
    name: Dr. Pragati Rajput
    display_name: Dr. Pragati
    avatar: goutham-reddy.jpeg
    gravatar: gouthamreddy51297
    email: contact@gouthamreddy.com
    web: https://gouthamreddy.com
    twitter: https://twitter.com/iamgouthamreddy
    description: "Historian"
  Charan:
    name: Charan
    display_name: Charan Reddy
    avatar: goutham-reddy.jpeg
    gravatar: gouthamreddy51297
    email: contact@gouthamreddy.com
    web: https://gouthamreddy.com
    twitter: https://twitter.com/iamgouthamreddy
    description: "zero"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
